Avans.Studentenhuis/Avans.Studentenhuis/Controllers/MealsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Avans.Studentenhuis.Data.Interfaces;
using Avans.Studentenhuis.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Avans.Studentenhuis.Controllers
{
    [Authorize]
    public class MealsController : Controller
    {
        private readonly IMealRepository _mealRepository;
        private readonly UserManager<Student> _userManager;

        public MealsController(IMealRepository mealRepository, UserManager<Student> userManager)
        {
            _mealRepository = mealRepository;
            _userManager = userManager;
        }

        // GET: Meals
        [AllowAnonymous]
        public IActionResult Index()
        {
            var meals = _mealRepository.GetAllWithCookBetween(DateTime.Today, DateTime.Today.AddDays(14));
            return View(meals);
        }

        // GET: Meals/Details/5
        [AllowAnonymous]
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = _mealRepository.GetWithParticipants((Guid)id);

            if (meal == null)
            {
                return NotFound();
            }

            return View(meal);
        }

        // GET: Meals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Meals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateTime,Name,Description,MaxParticipants,Price")] Meal meal)
        {
            // TODO: Replace this with MealDateIsUnique attribute on the Meal model. Maybe someday. :-(
            if (_mealRepository.GetAll().Any(e => e.DateTime.Date.CompareTo(meal.DateTime.Date) == 0))
            {
                // The ValidationSummary flag will only display added model errors for empty keys, sadly.
                ModelState.AddModelError(string.Empty, "There is already a meal planned on this date.");
            }

            if (ModelState.IsValid)
            {
                meal.Id = Guid.NewGuid();
                meal.Cook = await _userManager.GetUserAsync(User);

                _mealRepository.Create(meal);
                return RedirectToAction(nameof(Index));
            }

            return View(meal);
        }

        // GET: Meals/Participate/5
        public async Task<IActionResult> Participate(Guid id)
        {
            var meal = _mealRepository.GetWithParticipants(id);
            if (meal == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null || !meal.CanParticipate(user))
            {
                return Forbid();
            }

            var mealStudent = new MealStudent(meal, user);
            meal.Participants.Add(mealStudent);
            _mealRepository.Update(meal);
            
            return RedirectToAction(nameof(Index));
        }

        // GET: Meals/Cancel/5
        public async Task<IActionResult> Cancel(Guid id)
        {
            var meal = _mealRepository.GetWithParticipants(id);
            if (meal == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null || !meal.CanCancel(user))
            {
                return Forbid();
            }

            var mealStudent = meal.Participants.First(e => e.Student == user);
            meal.Participants.Remove(mealStudent);
            _mealRepository.Update(meal);

            return RedirectToAction(nameof(Index));
        }

        // GET: Meals/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = _mealRepository.GetWithParticipants((Guid) id);
            if (meal == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null || !meal.CanEdit(user))
            {
                return Forbid();
            }

            return View(meal);
        }

        // POST: Meals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("DateTime,Name,Description,MaxParticipants,Price")] Meal meal)
        {
            if (id != meal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _mealRepository.Update(meal);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MealExists(meal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(meal);
        }

        // GET: Meals/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = _mealRepository.GetWithParticipants((Guid) id);
            if (meal == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (user == null || !meal.CanDelete(user))
            {
                return Forbid();
            }

            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var meal = _mealRepository.GetById(id);
            _mealRepository.Delete(meal);
            return RedirectToAction(nameof(Index));
        }

        private bool MealExists(Guid id)
        {
            return _mealRepository.Find(e => e.Id == id).ToList().Count > 0;
        }
    }
}

Avans.Studentenhuis/Avans.Studentenhuis/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avans.Studentenhuis</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Avans.Studentenhuis</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Meals" asp-action="Index">Meals</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

<div class="container body-content" style="margin-top: 20px;">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            @RenderBody()
            <hr/>
            <footer>
                <p>&copy; 2018 - Avans.Studentenhuis</p>
            </footer>
        </div>

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
            @await Component.InvokeAsync("SidebarComponent")
        </div>
    </div>
</div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
</body>
</html>

Avans.Studentenhuis/Avans.Studentenhuis/Views/Shared/_TodaysMealPartial.cshtml
@model TodaysMealViewModel

<div class="panel panel-default">
    <div class="panel-heading">Today's Meal</div>
    <div class="panel-body">
        @if (Model?.Meal == null)
        {
            <p>There is no meal scheduled for today.</p>
        }
        else
        {
            <p>
                @Html.DisplayNameFor(model => model.Meal.DateTime): @Html.DisplayFor(model => model.Meal.DateTime)<br />
                @Html.DisplayNameFor(model => model.Meal.Name): @Html.DisplayFor(model => model.Meal.Name)<br />
                @Html.DisplayNameFor(model => model.Meal.Price): @Html.DisplayFor(model => model.Meal.Price)<br />
                @Html.DisplayNameFor(model => model.Meal.Cook): @Html.DisplayFor(model => model.Meal.Cook.FullName)<br /><br />
                <a asp-controller="Meals" asp-action="Details" asp-route-id="@Model.Meal.Id">More information...</a>
            </p>
        }
    </div>
</div>